<?php

namespace RWP;

/**
 * Determine if a post was generated by RWP.
 *
 * @param int $post_id The ID of the post.
 * @return bool True if generated by RWP. False if not.
 */
function is_generated( $post_id = 0 ) {
	if ( 0 === $post_id ) {
		$post_id = get_queried_object_id();
	}

	$rwp_generated = get_post_meta( $post_id, 'rwp_generated', true );

	if ( $rwp_generated ) {
		return true;
	}

	return false;
}
